name: 'Terraform Deploy'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

#      # Configure AWS credentials
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
#          aws-region: var.AWS_REGION

      - name: Set Terraform log level
        run: echo "TF_LOG=DEBUG" >> $GITHUB_ENV

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Plan the Terraform deployment
      - name: Terraform Plan
        run: terraform plan -var "DB_NAME=${{ env.DB_NAME }}" -var "DB_USERNAME=${{ env.DB_USERNAME }}" -var "DB_PASSWORD=${{ env.DB_PASSWORD }}" -var "AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}" -var "AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}" -var "AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }}" -var "AWS_REGION=${{ env.AWS_REGION }}"

      # Apply the Terraform configuration
      - name: Terraform Apply
        run: terraform apply --auto-approve